### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by dpsanders** [epn/Star.jl#1]
Could you please add a license, preferably MIT?

**Comment by epn** [comment]
How to do that?

**Comment by dpsanders** [comment]
Just add a file called `LICENSE.md` at the root of the repository, with the license content, e.g.

https://opensource.org/licenses/MIT

where you put your name and the year.

If you use `Pkg.generate()`, this will be done automatically and you will get the structure of a Julia package.

**Comment by epn** [comment]
ok. thanks. i just added the MIT license.

**Comment by dpsanders** [comment]
Great, thanks!
